# .travis.yml
language: node_js

node_js:
  - 6

install:
  - ./prepare.sh

script:
  - ./package.sh

deploy:
  provider: s3
  region: ap-northeast-2
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  skip_cleanup: true
  acl: public_read
  local_dir: target
  upload-dir: maven2/com/nalbam/nalbam-resize

notifications:
  slack: $SLACK_KEY
