version: 0.1

environment_variables:
  plaintext:

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Build started on `date`
      - bash prepare.sh
  build:
    commands:
      - echo Nothing to do in the build phase...
  post_build:
    commands:
      - bash package.sh
      - echo Build completed on `date`
artifacts:
  discard-paths: yes
  files:
    - target/*.zip
