#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/workspace
    steps:
      - checkout
      - run: mkdir -p target
      - run: cd src && npm run build
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/workspace
  deploy:
    docker:
      - image: nalbam/builder
    working_directory: ~/workspace
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: pwd && ls -al
      - run: cd src && zip -r ../target/lambda.zip *
      - run: terraform init
      - run: terraform apply -auto-approve -var="version=1.0.${CIRCLE_BUILD_NUM}"

workflows:
  version: 2
  lambda:
    jobs:
      - build
      - deploy:
          requires:
            - build
