#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: nalbam/builder
    working_directory: ~/workspace
    steps:
      - checkout
      - run: mkdir -p target
      - run: cd src && npm run build
      - run: pwd && ls -al
      - run: cd src && zip -r ../target/lambda.zip *
      - run: terraform init
      - run: terraform apply -auto-approve -var="version=1.0.${CIRCLE_BUILD_NUM}"

workflows:
  version: 2
  lambda:
    jobs:
      - build
